//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressStudents
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discipline
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Discipline()
        {
            this.Summary = new HashSet<Summary>();
        }
    
        public int DisciplineID { get; set; }
        public string DisciplineName { get; set; }
        public int DisciplinePulpit { get; set; }
        public int DisciplineHours { get; set; }
        public int DisciplineFormatControl { get; set; }
        public int DisciplineTeacher { get; set; }
    
        public virtual Pulpit Pulpit { get; set; }
        public virtual FormatControl FormatControl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Summary> Summary { get; set; }
        public virtual Teachers Teachers { get; set; }
    }
}
