//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressStudents
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Progress_StudentsEntities : DbContext
    {
        private static Progress_StudentsEntities _contetx;
        public static Progress_StudentsEntities GetContext()
        {
            if (_contetx == null)
                _contetx = new Progress_StudentsEntities();
            return _contetx;
        }
        public Progress_StudentsEntities()
            : base("name=Progress_StudentsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Class> Class { get; set; }
        public virtual DbSet<Discipline> Discipline { get; set; }
        public virtual DbSet<Faculty> Faculty { get; set; }
        public virtual DbSet<FormatControl> FormatControl { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<Pulpit> Pulpit { get; set; }
        public virtual DbSet<Students> Students { get; set; }
        public virtual DbSet<SubordinatesSummary> SubordinatesSummary { get; set; }
        public virtual DbSet<Summary> Summary { get; set; }
        public virtual DbSet<Teachers> Teachers { get; set; }
        public virtual DbSet<stud> stud { get; set; }
    }
}
