//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressStudents
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Students()
        {
            this.SubordinatesSummary = new HashSet<SubordinatesSummary>();
        }
    
        public int StudentID { get; set; }
        public string StudentSurname { get; set; }
        public string StudentName { get; set; }
        public string StudentPatronymic { get; set; }
        public int StudentClass { get; set; }
        public System.DateTime StudentDateOfBirth { get; set; }
        public int StudentGender { get; set; }
        public string StudentAdress { get; set; }
        public string StudentCity { get; set; }
        public string StudentPhoneNumber { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubordinatesSummary> SubordinatesSummary { get; set; }
    }
}
